import { askFollowUp } from '../api.js';
import FollowUpChat from './FollowUpChat.jsx';

const IMPACT_TONE = { positive: 'positive', negative: 'negative', mixed: 'mixed' };

/** Result of the Gemini summary for the article, framed around the focus ticker. */
export default function SummaryPanel({ state, articleId, ticker, onRetry }) {
  if (state.status === 'idle') return null;

  if (state.status === 'loading') {
    return (
      <section className="summary" aria-live="polite" aria-busy="true">
        <p className="summary-head">AI summary · {ticker}</p>
        <p className="muted">Asking Gemini to summarize this article for {ticker}…</p>
        <div className="summary-skeleton" aria-hidden="true">
          <span />
          <span />
          <span />
        </div>
      </section>
    );
  }

  if (state.status === 'error') {
    return (
      <section className="summary summary-error" role="alert">
        <p className="summary-head">AI summary · {ticker}</p>
        <p>
          {state.error}{' '}
          <button type="button" className="link-button" onClick={onRetry}>
            Try again
          </button>
        </p>
      </section>
    );
  }

  const s = state.data;
  return (
    <section className="summary" aria-live="polite">
      <p className="summary-head">
        <span>AI summary · {s.ticker}</span>
        {s.impact && <span className={`pill tone-bg-${IMPACT_TONE[s.impact] ?? 'neutral'}`}>impact: {s.impact}</span>}
        {s.relevance && <span className="pill">relevance: {s.relevance}</span>}
      </p>

      {s.summary && <p>{s.summary}</p>}

      {s.tickerImpact && (
        <div>
          <h2>What it means for {s.ticker}</h2>
          <p>{s.tickerImpact}</p>
        </div>
      )}

      {s.marketContext && (
        <div>
          <h2>Market context</h2>
          <p>{s.marketContext}</p>
        </div>
      )}

      {s.keyPoints.length > 0 && (
        <div>
          <h2>Key points</h2>
          <ul className="summary-points">
            {s.keyPoints.map((point, i) => (
              <li key={i}>{point}</li>
            ))}
          </ul>
        </div>
      )}

      <FollowUpChat
        cacheKey={`article:${articleId}:${s.ticker}:${s.generatedAt}`}
        suggestions={s.followUps ?? []}
        placeholder={`e.g. “What does beating EPS expectations mean for ${s.ticker}?”  (Enter to send)`}
        onAsk={(messages, signal) => askFollowUp(articleId, s.ticker, { summary: s, messages }, signal)}
      />

      <p className="muted small">
        Generated by {s.model} from this article only — answers can be wrong; check the text below. Not investment advice.{' '}
        <button type="button" className="link-button" onClick={onRetry}>
          Regenerate
        </button>
      </p>
    </section>
  );
}
